@startuml MainClass

class MainClass {
    -firstVariable: double
    -secondVariable: double

    +MainClass()
    +MainClass(firstVariable: double, secondVariable: double)

    +setFirstVariable(double)
    +getFirstVariable(): double
    +setSecondtVariable(double)
    +getSecondVariable(): double

    +getFunction(): double
    +getFunction2(): double
}

@enduml

Use Case Diagrams are meant to be kept simple, and easy to read.
A quick glance could help somebody understand the basic idea of what
is supposed to happen.

Below is a PlantUML code to create a sample UML using PlantUML
in either IntelliJ or VS Code with the added extensions.
